#!/usr/bin/env bash
# Protemu-owned flow for an emitted hardcaml_asic bundle. Each step is explicit;
# only "run" starts LibreLane, and only "postcheck" runs physical postchecks.
set -euo pipefail

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
repo_root=$(cd "$script_dir/../.." && pwd)
tt_dir="$repo_root/tinytapeout"
runner="$script_dir/adopted_phase4.py"
reporter="$script_dir/adopted_report.py"

out=${PROTEMU_FLOW_OUT:-$tt_dir/build/adopted}
case $out in /*) ;; *) out="$PWD/$out" ;; esac
bundle=${PROTEMU_BUNDLE:-$out/bundle}
runs=${PROTEMU_RUNS:-$out/runs}
run_dir=${PROTEMU_RUN:-}
for name in bundle runs run_dir; do
    value=${!name}
    if [[ -n $value && $value != /* ]]; then printf -v "$name" '%s' "$PWD/$value"; fi
done
allow_python_mismatch=${PROTEMU_ALLOW_PYTHON_MISMATCH:-1}

usage() {
    cat <<'USAGE'
Usage: tinytapeout/scripts/adopted-flow.sh STEP [STEP ...]

Steps, run only when named:
  bootstrap   Provision scaf-owned collateral and Docker image; skip legacy staging
  emit        Build and write the immutable adopted bundle into $PROTEMU_FLOW_OUT/bundle
  preflight   Validate bundle, collateral, versions, image, and configuration
  run         Start the physical flow; creates a new run under $PROTEMU_RUNS
  postcheck   TT precheck and gate-level wrapper simulation after a full run
  collect     Write results.json for a run
  report      Print the physical/timing summary for a run

Set PROTEMU_FLOW_OUT to a new directory for each emitted build. Separate
postcheck/collect/report invocations need PROTEMU_RUN set to the printed run
directory. Override collateral paths with PROTEMU_TT, PROTEMU_PDK_ROOT,
PROTEMU_FLOW_PY, and PROTEMU_PRECHECK_PY. Defaults come from scaf's bootstrap.
Set PROTEMU_STAGE=synthesis for a mapped-synthesis-only run (default: full).
Set PROTEMU_ALLOW_PYTHON_MISMATCH=0 to require the exact requested minor version.
USAGE
}

if [[ $# -eq 0 ]]; then usage; exit 0; fi
for step in "$@"; do
    case $step in
        bootstrap|emit|preflight|run|postcheck|collect|report) ;;
        -h|--help) usage; exit 0 ;;
        *) echo "adopted-flow: unknown step: $step" >&2; exit 2 ;;
    esac
done

load_toolchain() {
    local env_file="$tt_dir/build/toolchain-env.sh"
    if [[ -f $env_file ]]; then
        # Generated by this repository's bootstrap, never by a sibling checkout.
        # shellcheck disable=SC1090
        source "$env_file"
    fi
    tool_tt=${PROTEMU_TT:-${TT_SUPPORT_TOOLS_DIR:-$tt_dir/tt}}
    tool_pdk=${PROTEMU_PDK_ROOT:-${PDK_ROOT:-$tt_dir/pdk}}
    tool_python=${PROTEMU_FLOW_PY:-$repo_root/.venv/bin/python}
    tool_precheck_python=${PROTEMU_PRECHECK_PY:-$repo_root/.venv-precheck/bin/python}
    if [[ ! -d $tool_tt || ! -d $tool_pdk || ! -x $tool_python ]]; then
        echo "adopted-flow: collateral missing; run this script with bootstrap" >&2
        echo "adopted-flow: or set PROTEMU_TT, PROTEMU_PDK_ROOT, and PROTEMU_FLOW_PY" >&2
        return 2
    fi
}

mismatch_args=()
case $allow_python_mismatch in
    0) ;;
    1) mismatch_args=(--allow-python-mismatch) ;;
    *) echo "adopted-flow: PROTEMU_ALLOW_PYTHON_MISMATCH must be 0 or 1" >&2; exit 2 ;;
esac

need_run() {
    if [[ -z $run_dir || ! -f $run_dir/run.json ]]; then
        echo "adopted-flow: set PROTEMU_RUN to the run directory printed by 'run'" >&2
        return 2
    fi
}

step_bootstrap() {
    "$script_dir/bootstrap-toolchain.sh" --adopted-only
}

step_emit() {
    if [[ -d $bundle && -n $(ls -A "$bundle" 2>/dev/null) ]]; then
        echo "adopted-flow: bundle is not empty: $bundle" >&2
        echo "adopted-flow: choose a new PROTEMU_FLOW_OUT" >&2
        return 2
    fi
    (cd "$repo_root" && dune build bin/asic_bundle.exe && \
        _build/default/bin/asic_bundle.exe "$bundle" "$repo_root")
}

step_preflight() {
    load_toolchain
    mkdir -p "$out"
    python3 "$runner" preflight "$bundle" \
        --support-tools "$tool_tt" --pdk-root "$tool_pdk" \
        --python "$tool_python" "${mismatch_args[@]}" \
        --output "$out/preflight.json"
}

step_run() {
    load_toolchain
    local stage=${PROTEMU_STAGE:-full} record status=0
    [[ $stage == full || $stage == synthesis ]] || {
        echo "adopted-flow: PROTEMU_STAGE must be full or synthesis" >&2; return 2;
    }
    mkdir -p "$runs"
    echo "adopted-flow: starting LibreLane $stage; results will be under $runs" >&2
    record=$(python3 "$runner" run "$bundle" \
        --support-tools "$tool_tt" --pdk-root "$tool_pdk" \
        --python "$tool_python" "${mismatch_args[@]}" \
        --runs "$runs" --stage "$stage") || status=$?
    if [[ -f $record ]]; then
        run_dir=$(dirname "$record")
        [[ ! -f $out/preflight.json ]] || cp "$out/preflight.json" "$run_dir/preflight.json"
        echo "adopted-flow: run directory $run_dir" >&2
    else
        echo "adopted-flow: no run record returned: $record" >&2
    fi
    return "$status"
}

step_postcheck() {
    need_run
    load_toolchain
    [[ -x $tool_precheck_python ]] || {
        echo "adopted-flow: precheck Python missing: $tool_precheck_python" >&2; return 2;
    }
    python3 "$runner" postcheck "$run_dir" \
        --support-tools "$tool_tt" --pdk-root "$tool_pdk" \
        --precheck-python "$tool_precheck_python" \
        --testbench "$tt_dir/test/tb.v"
}

step_collect() {
    need_run
    python3 "$runner" collect "$run_dir" --output "$run_dir/results.json"
    echo "adopted-flow: results $run_dir/results.json"
}

step_report() {
    need_run
    python3 "$reporter" "$run_dir"
}

for step in "$@"; do "step_$step"; done
