(library
 (name protemu_protocol_core_tests)
 (wrapped false)
 (modules
  protocol_core_testbench
  protocol_core_unit_tests
  protocol_core_property_tests)
 ; Keep the ppx_expect source-tree workaround described in test/common/dune.
 (inline_tests
  (flags
   (:standard -source-tree-root .)))
 (libraries
  core
  hardcaml
  hardcaml_protemu
  protemu_f_model
  protemu_test_common
  base_quickcheck
  splittable_random)
 (preprocess
  (pps ppx_hardcaml ppx_jane))
 (lint
  (pps ppx_js_style))
 (flags
  (:standard -w -27-57-33-34-35-40-63-47-26)))
